name: sp500-signal-classifier
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - pyyaml
  - python-dateutil
  - pip
  - ipykernel
  - pip:
    - yfinance
    - ta
    - black
    - isort
    - pre-commit
